---
# Download kind (K8s)
   - name: Install kind
     ansible.builtin.shell: |
       curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
       chmod +x ./kind
       mv ./kind /usr/local/bin/kind
     args:
      creates: /usr/local/bin/kind

# Create file config whit static ip
   - name: Crea file di configurazione Kind con IP statico
     ansible.builtin.copy:
      dest: /tmp/kind-config.yaml
      content: |
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        

# Check cluster monitoring-webapp-cluster   
   - name: Check if Kind cluster already exists
     ansible.builtin.shell: kind get clusters
     register: kind_clusters
     environment:
      PATH: "/usr/local/bin:/usr/bin:/bin"

# Create cluster monitoring-webapp-cluster
   - name: Create Kind cluster if not exists
     ansible.builtin.command:
      cmd: kind create cluster --name monitoring-webapp-cluster 
     when: "'monitoring-webapp-cluster' not in kind_clusters.stdout"
     environment:
      PATH: "/usr/local/bin:/usr/bin:/bin"

# # Connetti il nodo Kind alla rete docker
#    - name: Connect Kind node to Docker_network
#      ansible.builtin.command:
#       cmd: docker network connect Docker_network monitoring-webapp-cluster-control-plane
